#!/bin/sh

LIB_DIR=`dirname $0`/../lib
TEMP_DIR=`mktemp -d -t domina_libs`

curl http://selenium.googlecode.com/files/selenium-java-2.15.0.zip -o $TEMP_DIR/selenium.zip
unzip $TEMP_DIR/selenium.zip -d $TEMP_DIR

F1=$TEMP_DIR/selenium-2.15.0/selenium-java-2.15.0.jar
cp $F1 $LIB_DIR/.
cp $TEMP_DIR/selenium-2.15.0/libs/*.jar $LIB_DIR/.

rm -rf $TEMP_DIR

