#!/bin/sh

CP=''
CP=$CP:$CLOJURESCRIPT_HOME/lib/*
CP=$CP:$CLOJURESCRIPT_HOME/src/clj
CP=$CP:$CLOJURESCRIPT_HOME/src/cljs

PROJECT_DIR=`dirname $0`/..

CP=$CP:$PROJECT_DIR/lib/*
CP=$CP:$PROJECT_DIR/lib

CP=$CP:$PROJECT_DIR/src/cljs
CP=$CP:$PROJECT_DIR/src/clj
CP=$CP:$PROJECT_DIR/test/cljs
CP=$CP:$PROJECT_DIR/test/clj

echo using classpath: $CP
export CLASSPATH=$CP
